DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS topic;
DROP TABLE IF EXISTS bills;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE topics (
  userid INTEGER NOT NULL,
  topic TEXT NOT NULL
);

CREATE TABLE bills (
  userid INTEGER NOT NULL,
  topic TEXT NOT NULL
  total REAL NOT NULL,
  posted_date TEXT NOT NULL,
  due_date TEXT NOT NULL
);
