DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS bills;
DROP TABLE IF EXISTS topics;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE topics (
  id INTEGER PRIMARY KEY;
  topic TEXT NOT NULL;
  FOREIGN KEY (id) REFERENCES user (id)
    ON DELETE SET NULL
   );

CREATE TABLE bills (
  id INTEGER PRIMARY KEY,
  topic TEXT NOT NULL,
  name TEXT NOT NULL.
  total REAL NOT NULL,
  posted_date TEXT NOT NULL,
  due_date TEXT NOT NULL,
  FOREIGN KEY (id) REFERENCES user (id),
  FOREIGN KEY (topic) REFERENCES topics (topic) 
);
