DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS bills;
DROP TABLE IF EXISTS topics;
DROP TABLE IF EXISTS groups;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE topics (
  id INTEGER,
  topic TEXT NOT NULL,
  FOREIGN KEY (id) REFERENCES user (id)
);

CREATE TABLE bills (
  id INTEGER NOT NULL,
  bill_id INTEGER PRIMARY KEY AUTOINCREMENT,
  topic TEXT NOT NULL,
  total REAL NOT NULL,
  posted_date TEXT,
  due_date TEXT NOT NULL,
  paid INTEGER NOT NULL,
  past_due INTEGER NOT NULL,
  group_id INTEGER,
  FOREIGN KEY (id) REFERENCES user (id),
  FOREIGN KEY (topic) REFERENCES topics (topic)
);

CREATE TABLE groups (
  group_id INTEGER PRIMARY KEY AUTOINCREMENT,
  owner_id INTEGER NOT NULL,
  name TEXT NOT NULL
);
